{% set name = "large-image-source-gdal" %}
{% set version = "1.32.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: fb34fc0cb1ccad2d730131b670a350dd089f97c198b0dbe7166c86d6994cc0f2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - large-image >=1.14.2
    - gdal
    - pyproj >=2.2.0
    - packaging

test:
  requires:
    - python {{ python_min }}
  imports:
    - large_image
    - large_image_source_gdal
  commands:
    - python -c "import large_image; large_image.tilesource.loadTileSources(); assert 'gdal' in large_image.tilesource.AvailableTileSources"

about:
  home: https://github.com/girder/large_image
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Python modules to work with large, multiresolution images - GDAL source
  description: |
    Python modules to work with large, multiresolution images - GDAL source. Large Image is developed and maintained by the Data & Analytics group at Kitware, Inc. for processing large geospatial and medical images.
  doc_url: https://girder.github.io/large_image/
  dev_url: https://github.com/girder/large_image

extra:
  recipe-maintainers:
    - banesullivan
    - manthey
    - giswqs
